<?xml version="1.0" encoding="utf-8"?><Database Name="DB_99F084_dima" Class="PentagoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SQL5007.Smarterasp.net;Initial Catalog=DB_99F084_dima;User ID=DB_99F084_dima_admin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_99F084_dimaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PentagoGame" Member="PentagoGames">
    <Type Name="PentagoGame">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HostKey" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="JoinKey" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DateStarted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateEnded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GameCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HostIsCross" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsGameEnded" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GameField" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="HostName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="JoinName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsHostTurn" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>