#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal_Website.Projects.Pentago
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_99F084_dima")]
	public partial class PentagoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPentagoGame(PentagoGame instance);
    partial void UpdatePentagoGame(PentagoGame instance);
    partial void DeletePentagoGame(PentagoGame instance);
    #endregion
		
		public PentagoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_99F084_dimaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PentagoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PentagoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PentagoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PentagoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PentagoGame> PentagoGames
		{
			get
			{
				return this.GetTable<PentagoGame>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PentagoGame")]
	public partial class PentagoGame : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _HostKey;
		
		private string _JoinKey;
		
		private System.Nullable<System.DateTime> _DateStarted;
		
		private System.Nullable<System.DateTime> _DateEnded;
		
		private string _GameCode;
		
		private bool _HostIsCross;
		
		private System.Nullable<bool> _IsGameEnded;
		
		private string _GameField;
		
		private string _HostName;
		
		private string _JoinName;
		
		private bool _IsHostTurn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHostKeyChanging(string value);
    partial void OnHostKeyChanged();
    partial void OnJoinKeyChanging(string value);
    partial void OnJoinKeyChanged();
    partial void OnDateStartedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateStartedChanged();
    partial void OnDateEndedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateEndedChanged();
    partial void OnGameCodeChanging(string value);
    partial void OnGameCodeChanged();
    partial void OnHostIsCrossChanging(bool value);
    partial void OnHostIsCrossChanged();
    partial void OnIsGameEndedChanging(System.Nullable<bool> value);
    partial void OnIsGameEndedChanged();
    partial void OnGameFieldChanging(string value);
    partial void OnGameFieldChanged();
    partial void OnHostNameChanging(string value);
    partial void OnHostNameChanged();
    partial void OnJoinNameChanging(string value);
    partial void OnJoinNameChanged();
    partial void OnIsHostTurnChanging(bool value);
    partial void OnIsHostTurnChanged();
    #endregion
		
		public PentagoGame()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HostKey", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HostKey
		{
			get
			{
				return this._HostKey;
			}
			set
			{
				if ((this._HostKey != value))
				{
					this.OnHostKeyChanging(value);
					this.SendPropertyChanging();
					this._HostKey = value;
					this.SendPropertyChanged("HostKey");
					this.OnHostKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JoinKey", DbType="VarChar(MAX)")]
		public string JoinKey
		{
			get
			{
				return this._JoinKey;
			}
			set
			{
				if ((this._JoinKey != value))
				{
					this.OnJoinKeyChanging(value);
					this.SendPropertyChanging();
					this._JoinKey = value;
					this.SendPropertyChanged("JoinKey");
					this.OnJoinKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateStarted", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateStarted
		{
			get
			{
				return this._DateStarted;
			}
			set
			{
				if ((this._DateStarted != value))
				{
					this.OnDateStartedChanging(value);
					this.SendPropertyChanging();
					this._DateStarted = value;
					this.SendPropertyChanged("DateStarted");
					this.OnDateStartedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEnded", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateEnded
		{
			get
			{
				return this._DateEnded;
			}
			set
			{
				if ((this._DateEnded != value))
				{
					this.OnDateEndedChanging(value);
					this.SendPropertyChanging();
					this._DateEnded = value;
					this.SendPropertyChanged("DateEnded");
					this.OnDateEndedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GameCode
		{
			get
			{
				return this._GameCode;
			}
			set
			{
				if ((this._GameCode != value))
				{
					this.OnGameCodeChanging(value);
					this.SendPropertyChanging();
					this._GameCode = value;
					this.SendPropertyChanged("GameCode");
					this.OnGameCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HostIsCross", DbType="Bit NOT NULL")]
		public bool HostIsCross
		{
			get
			{
				return this._HostIsCross;
			}
			set
			{
				if ((this._HostIsCross != value))
				{
					this.OnHostIsCrossChanging(value);
					this.SendPropertyChanging();
					this._HostIsCross = value;
					this.SendPropertyChanged("HostIsCross");
					this.OnHostIsCrossChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsGameEnded", DbType="Bit")]
		public System.Nullable<bool> IsGameEnded
		{
			get
			{
				return this._IsGameEnded;
			}
			set
			{
				if ((this._IsGameEnded != value))
				{
					this.OnIsGameEndedChanging(value);
					this.SendPropertyChanging();
					this._IsGameEnded = value;
					this.SendPropertyChanged("IsGameEnded");
					this.OnIsGameEndedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameField", DbType="VarChar(MAX)")]
		public string GameField
		{
			get
			{
				return this._GameField;
			}
			set
			{
				if ((this._GameField != value))
				{
					this.OnGameFieldChanging(value);
					this.SendPropertyChanging();
					this._GameField = value;
					this.SendPropertyChanged("GameField");
					this.OnGameFieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HostName", DbType="NVarChar(MAX)")]
		public string HostName
		{
			get
			{
				return this._HostName;
			}
			set
			{
				if ((this._HostName != value))
				{
					this.OnHostNameChanging(value);
					this.SendPropertyChanging();
					this._HostName = value;
					this.SendPropertyChanged("HostName");
					this.OnHostNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JoinName", DbType="NVarChar(MAX)")]
		public string JoinName
		{
			get
			{
				return this._JoinName;
			}
			set
			{
				if ((this._JoinName != value))
				{
					this.OnJoinNameChanging(value);
					this.SendPropertyChanging();
					this._JoinName = value;
					this.SendPropertyChanged("JoinName");
					this.OnJoinNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHostTurn", DbType="Bit NOT NULL")]
		public bool IsHostTurn
		{
			get
			{
				return this._IsHostTurn;
			}
			set
			{
				if ((this._IsHostTurn != value))
				{
					this.OnIsHostTurnChanging(value);
					this.SendPropertyChanging();
					this._IsHostTurn = value;
					this.SendPropertyChanged("IsHostTurn");
					this.OnIsHostTurnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
