//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal_Website.Projects.Grades {
    
    
    public partial class Default {
        
        /// <summary>
        /// CSIQP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Personal_Website.Projects.Grades.GradesTable CSIQP;
        
        /// <summary>
        /// Math control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Personal_Website.Projects.Grades.GradesTable Math;
        
        /// <summary>
        /// Science control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Personal_Website.Projects.Grades.GradesTable Science;
        
        /// <summary>
        /// SocScinces control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Personal_Website.Projects.Grades.GradesTable SocScinces;
        
        /// <summary>
        /// Breadth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Personal_Website.Projects.Grades.GradesTable Breadth;
        
        /// <summary>
        /// Depth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Personal_Website.Projects.Grades.GradesTable Depth;
        
        /// <summary>
        /// Seminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Personal_Website.Projects.Grades.GradesTable Seminar;
        
        /// <summary>
        /// PE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Personal_Website.Projects.Grades.GradesTable PE;
        
        /// <summary>
        /// IQP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Personal_Website.Projects.Grades.GradesTable IQP;
        
        /// <summary>
        /// FreeElect control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Personal_Website.Projects.Grades.GradesTable FreeElect;
    }
}
