<?xml version="1.0" encoding="utf-8"?><Database Name="GradesDB" Class="GradesDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\v11.0;Initial Catalog=GradesDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GradesDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SimpleGrades" Member="SimpleGrades">
    <Type Name="SimpleGrade">
      <Column Name="term" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="courseID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="gradePercent" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="gradeLetter" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>